CREATE DATABASE `nagios` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'ndoutils'@'%' IDENTIFIED BY 'NDOUTILSDEFAULTPASSWORD';
GRANT ALL PRIVILEGES ON `nagios`.* TO 'ndoutils'@'%' WITH GRANT OPTION;
GRANT PROCESS ON *.* TO 'ndoutils'@'%';
FLUSH PRIVILEGES;

