services:
  nagiosxi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MYSQL_HOST: ${MYSQL_HOST}
        MYSQL_PORT: ${MYSQL_PORT}
        MYSQL_ROOT_PASS: ${MYSQL_ROOT_PASS}
    environment:
      TZ: America/Toronto
      GLOBAL_MYSQL_HOST: ${MYSQL_HOST}
    ports:
      - "80:80"
      - "5666:5666"
      - "5667:5667"

