version: '3.8'

services:
  nagios-csp:
    build:
      context: ./nagios-csp
      dockerfile: Dockerfile
    container_name: nagios-csp
    restart: unless-stopped
    networks:
      - my_network
    ports:
      - "8080:80"   # Web UI
      - "5667:5667" # NRPE (Nagios Remote Plugin Executor)
    volumes:
      - nagios_data:/usr/local/nagios
      - mysql_data:/var/lib/mysql

volumes:
  nagios_data:
  mysql_data:

networks:
  my_network:
